/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DashboardCountsDto {
  answeredTickets?: number;
  draftTickets?: number;
  openTickets?: number;
  solvedTickets?: number;
  totalTickets?: number;
}
