/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationDto {
  id?: number;
  isRead?: boolean;
  message?: string;
  ticketId?: number;
  userId?: number;
}
