/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SupportServiceResponse {
  categoryId?: number;
  categoryName?: string;
  description?: string;
  id?: number;
  title?: string;
}
