/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SupportServiceCreateRequest {
  categoryId: number;
  description?: string;
  title: string;
}
