/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TicketDto {
  assignedToUserId?: number;
  categoryId?: number;
  createdByUserId?: number;
  description?: string;
  id?: number;
  priority?: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  status?: 'OPEN' | 'IN_PROGRESS' | 'RESOLVED' | 'CLOSED' | 'REJECTED';
  title?: string;
}
