
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TicketHistoryDto {
  changedByUserId?: number;
  comment?: string;
  id?: number;
  newStatus?: 'OPEN' | 'IN_PROGRESS' | 'RESOLVED' | 'CLOSED' | 'REJECTED';
  oldStatus?: 'OPEN' | 'IN_PROGRESS' | 'RESOLVED' | 'CLOSED' | 'REJECTED';
  ticketId?: number;
}
