/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TicketHistoryDto {
  changedById?: string;
  changedByName?: string;
  createdOn?: string;
  id?: number;
  newStatus?: 'OPEN' | 'ANSWERED' | 'SOLVED' | 'DRAFT';
  note?: string;
  previousStatus?: 'OPEN' | 'ANSWERED' | 'SOLVED' | 'DRAFT';
  ticketId?: number;
}
