/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  email?: string;
  firstName?: string;
  fiscalCode?: string;
  id?: string;
  lastName?: string;
  phoneNumber?: string;
  role?: 'ADMIN' | 'HELPER_JUNIOR' | 'HELPER_SENIOR' | 'PM' | 'USER';
}
