/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TicketHistoryDto } from '../../models/ticket-history-dto';

export interface GetHistoryByTicket$Params {
  ticketId: number;
}

export function getHistoryByTicket(http: HttpClient, rootUrl: string, params: GetHistoryByTicket$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TicketHistoryDto>>> {
  const rb = new RequestBuilder(rootUrl, getHistoryByTicket.PATH, 'get');
  if (params) {
    rb.path('ticketId', params.ticketId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TicketHistoryDto>>;
    })
  );
}

getHistoryByTicket.PATH = '/api/v1/ticket-history/{ticketId}';
