/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getHistoryByTicket } from '../fn/ticket-history/get-history-by-ticket';
import { GetHistoryByTicket$Params } from '../fn/ticket-history/get-history-by-ticket';
import { TicketHistoryDto } from '../models/ticket-history-dto';

@Injectable({ providedIn: 'root' })
export class TicketHistoryService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getHistoryByTicket()` */
  static readonly GetHistoryByTicketPath = '/api/v1/ticket-history/{ticketId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getHistoryByTicket()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHistoryByTicket$Response(params: GetHistoryByTicket$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TicketHistoryDto>>> {
    return getHistoryByTicket(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getHistoryByTicket$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getHistoryByTicket(params: GetHistoryByTicket$Params, context?: HttpContext): Observable<Array<TicketHistoryDto>> {
    return this.getHistoryByTicket$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<TicketHistoryDto>>): Array<TicketHistoryDto> => r.body)
    );
  }

}
