/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CategoryDto } from './models/category-dto';
export type { CategoryResponse } from './models/category-response';
export type { DashboardCountsDto } from './models/dashboard-counts-dto';
export type { Pageable } from './models/pageable';
export type { PageableObject } from './models/pageable-object';
export type { PageTicketResponseDto } from './models/page-ticket-response-dto';
export type { SortObject } from './models/sort-object';
export type { SupportServiceCreateRequest } from './models/support-service-create-request';
export type { SupportServiceResponse } from './models/support-service-response';
export type { SupportServiceUpdateRequest } from './models/support-service-update-request';
export type { TicketHistoryDto } from './models/ticket-history-dto';
export type { TicketRequestDto } from './models/ticket-request-dto';
export type { TicketResponseDto } from './models/ticket-response-dto';
export type { UserContactUpdateRequest } from './models/user-contact-update-request';
export type { UserDto } from './models/user-dto';
