/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CategoryDto } from './models/category-dto';
export type { NotificationDto } from './models/notification-dto';
export type { TicketDto } from './models/ticket-dto';
export type { TicketHistoryDto } from './models/ticket-history-dto';
export type { UserDto } from './models/user-dto';
