/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { UserManagementService } from './services/user-management.service';
export { SupportServicesService } from './services/support-services.service';
export { CategoryService } from './services/category.service';
export { TicketManagementService } from './services/ticket-management.service';
export { TicketHistoryService } from './services/ticket-history.service';
