/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { create } from '../fn/support-services/create';
import { Create$Params } from '../fn/support-services/create';
import { delete$ } from '../fn/support-services/delete';
import { Delete$Params } from '../fn/support-services/delete';
import { getAll } from '../fn/support-services/get-all';
import { GetAll$Params } from '../fn/support-services/get-all';
import { getByCategory } from '../fn/support-services/get-by-category';
import { GetByCategory$Params } from '../fn/support-services/get-by-category';
import { SupportServiceResponse } from '../models/support-service-response';
import { update } from '../fn/support-services/update';
import { Update$Params } from '../fn/support-services/update';

@Injectable({ providedIn: 'root' })
export class SupportServicesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `update()` */
  static readonly UpdatePath = '/api/v1/services/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: Update$Params, context?: HttpContext): Observable<StrictHttpResponse<SupportServiceResponse>> {
    return update(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: Update$Params, context?: HttpContext): Observable<SupportServiceResponse> {
    return this.update$Response(params, context).pipe(
      map((r: StrictHttpResponse<SupportServiceResponse>): SupportServiceResponse => r.body)
    );
  }

  /** Path part for operation `delete()` */
  static readonly DeletePath = '/api/v1/services/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delete()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete$Response(params: Delete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return delete$(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete(params: Delete$Params, context?: HttpContext): Observable<void> {
    return this.delete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAll()` */
  static readonly GetAllPath = '/api/v1/services';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll$Response(params?: GetAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SupportServiceResponse>>> {
    return getAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAll(params?: GetAll$Params, context?: HttpContext): Observable<Array<SupportServiceResponse>> {
    return this.getAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SupportServiceResponse>>): Array<SupportServiceResponse> => r.body)
    );
  }

  /** Path part for operation `create()` */
  static readonly CreatePath = '/api/v1/services';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create$Response(params: Create$Params, context?: HttpContext): Observable<StrictHttpResponse<SupportServiceResponse>> {
    return create(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create(params: Create$Params, context?: HttpContext): Observable<SupportServiceResponse> {
    return this.create$Response(params, context).pipe(
      map((r: StrictHttpResponse<SupportServiceResponse>): SupportServiceResponse => r.body)
    );
  }

  /** Path part for operation `getByCategory()` */
  static readonly GetByCategoryPath = '/api/v1/services/category/{categoryId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getByCategory()` instead.
   *
   * This method doesn't expect any request body.
   */
  getByCategory$Response(params: GetByCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SupportServiceResponse>>> {
    return getByCategory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getByCategory$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getByCategory(params: GetByCategory$Params, context?: HttpContext): Observable<Array<SupportServiceResponse>> {
    return this.getByCategory$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SupportServiceResponse>>): Array<SupportServiceResponse> => r.body)
    );
  }

}
