
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createTicket } from '../fn/ticket/create-ticket';
import { CreateTicket$Params } from '../fn/ticket/create-ticket';
import { deleteTicket } from '../fn/ticket/delete-ticket';
import { DeleteTicket$Params } from '../fn/ticket/delete-ticket';
import { getAllTickets } from '../fn/ticket/get-all-tickets';
import { GetAllTickets$Params } from '../fn/ticket/get-all-tickets';
import { getTicketById } from '../fn/ticket/get-ticket-by-id';
import { GetTicketById$Params } from '../fn/ticket/get-ticket-by-id';
import { TicketDto } from '../models/ticket-dto';
import { updateTicket } from '../fn/ticket/update-ticket';
import { UpdateTicket$Params } from '../fn/ticket/update-ticket';

@Injectable({ providedIn: 'root' })
export class TicketService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getTicketById()` */
  static readonly GetTicketByIdPath = '/api/v1/tickets/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTicketById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTicketById$Response(params: GetTicketById$Params, context?: HttpContext): Observable<StrictHttpResponse<TicketDto>> {
    return getTicketById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTicketById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTicketById(params: GetTicketById$Params, context?: HttpContext): Observable<TicketDto> {
    return this.getTicketById$Response(params, context).pipe(
      map((r: StrictHttpResponse<TicketDto>): TicketDto => r.body)
    );
  }

  /** Path part for operation `updateTicket()` */
  static readonly UpdateTicketPath = '/api/v1/tickets/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateTicket()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTicket$Response(params: UpdateTicket$Params, context?: HttpContext): Observable<StrictHttpResponse<TicketDto>> {
    return updateTicket(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateTicket$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTicket(params: UpdateTicket$Params, context?: HttpContext): Observable<TicketDto> {
    return this.updateTicket$Response(params, context).pipe(
      map((r: StrictHttpResponse<TicketDto>): TicketDto => r.body)
    );
  }

  /** Path part for operation `deleteTicket()` */
  static readonly DeleteTicketPath = '/api/v1/tickets/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteTicket()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTicket$Response(params: DeleteTicket$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteTicket(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteTicket$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTicket(params: DeleteTicket$Params, context?: HttpContext): Observable<void> {
    return this.deleteTicket$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllTickets()` */
  static readonly GetAllTicketsPath = '/api/v1/tickets';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllTickets()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllTickets$Response(params?: GetAllTickets$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TicketDto>>> {
    return getAllTickets(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllTickets$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllTickets(params?: GetAllTickets$Params, context?: HttpContext): Observable<Array<TicketDto>> {
    return this.getAllTickets$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<TicketDto>>): Array<TicketDto> => r.body)
    );
  }

  /** Path part for operation `createTicket()` */
  static readonly CreateTicketPath = '/api/v1/tickets';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createTicket()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTicket$Response(params: CreateTicket$Params, context?: HttpContext): Observable<StrictHttpResponse<TicketDto>> {
    return createTicket(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createTicket$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTicket(params: CreateTicket$Params, context?: HttpContext): Observable<TicketDto> {
    return this.createTicket$Response(params, context).pipe(
      map((r: StrictHttpResponse<TicketDto>): TicketDto => r.body)
    );
  }

}
