/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DashboardCountsDto } from '../../models/dashboard-counts-dto';

export interface GetCounts$Params {
}

export function getCounts(http: HttpClient, rootUrl: string, params?: GetCounts$Params, context?: HttpContext): Observable<StrictHttpResponse<DashboardCountsDto>> {
  const rb = new RequestBuilder(rootUrl, getCounts.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DashboardCountsDto>;
    })
  );
}

getCounts.PATH = '/api/v1/tickets/counts';
