/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserDto } from '../../models/user-dto';

export interface GetUsersByRole$Params {

/**
 * Nome del ruolo da filtrare (es. 'USER')
 */
  roleName: 'ADMIN' | 'HELPER_JUNIOR' | 'HELPER_SENIOR' | 'PM' | 'USER';
}

export function getUsersByRole(http: HttpClient, rootUrl: string, params: GetUsersByRole$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserDto>>> {
  const rb = new RequestBuilder(rootUrl, getUsersByRole.PATH, 'get');
  if (params) {
    rb.query('roleName', params.roleName, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserDto>>;
    })
  );
}

getUsersByRole.PATH = '/api/v1/users/by-role';
