/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserDto } from '../../models/user-dto';

export interface UpdateUserRole$Params {

/**
 * ID dell'utente da aggiornare
 */
  userId: string;

/**
 * Il nuovo ruolo da assegnare
 */
  newRole: 'ADMIN' | 'HELPER_JUNIOR' | 'HELPER_SENIOR' | 'PM' | 'USER';
}

export function updateUserRole(http: HttpClient, rootUrl: string, params: UpdateUserRole$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
  const rb = new RequestBuilder(rootUrl, updateUserRole.PATH, 'patch');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.query('newRole', params.newRole, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserDto>;
    })
  );
}

updateUserRole.PATH = '/api/v1/users/{userId}/role';
