/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TicketResponseDto } from '../../models/ticket-response-dto';

export interface EscalateTicket$Params {

/**
 * ID del ticket da escalare
 */
  ticketId: number;

/**
 * ID del nuovo utente (helper/admin) a cui assegnare il ticket
 */
  newAssignedToId: string;
}

export function escalateTicket(http: HttpClient, rootUrl: string, params: EscalateTicket$Params, context?: HttpContext): Observable<StrictHttpResponse<TicketResponseDto>> {
  const rb = new RequestBuilder(rootUrl, escalateTicket.PATH, 'patch');
  if (params) {
    rb.path('ticketId', params.ticketId, {});
    rb.query('newAssignedToId', params.newAssignedToId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TicketResponseDto>;
    })
  );
}

escalateTicket.PATH = '/api/v1/tickets/{ticketId}/escalate';
