/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TicketRequestDto } from '../../models/ticket-request-dto';
import { TicketResponseDto } from '../../models/ticket-response-dto';

export interface UpdateTicket$Params {

/**
 * ID del ticket da aggiornare
 */
  ticketId: number;
      body: TicketRequestDto
}

export function updateTicket(http: HttpClient, rootUrl: string, params: UpdateTicket$Params, context?: HttpContext): Observable<StrictHttpResponse<TicketResponseDto>> {
  const rb = new RequestBuilder(rootUrl, updateTicket.PATH, 'put');
  if (params) {
    rb.path('ticketId', params.ticketId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TicketResponseDto>;
    })
  );
}

updateTicket.PATH = '/api/v1/tickets/{ticketId}';
