/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TicketResponseDto } from '../../models/ticket-response-dto';

export interface UpdateTicketStatus$Params {

/**
 * ID del ticket da aggiornare
 */
  ticketId: number;

/**
 * Nuovo stato del ticket
 */
  newStatus: 'OPEN' | 'ANSWERED' | 'SOLVED' | 'DRAFT';
}

export function updateTicketStatus(http: HttpClient, rootUrl: string, params: UpdateTicketStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<TicketResponseDto>> {
  const rb = new RequestBuilder(rootUrl, updateTicketStatus.PATH, 'patch');
  if (params) {
    rb.path('ticketId', params.ticketId, {});
    rb.query('newStatus', params.newStatus, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TicketResponseDto>;
    })
  );
}

updateTicketStatus.PATH = '/api/v1/tickets/{ticketId}/status';
